alias pk_create='packer build --var-file=../../packer_vars.json --var-file=../../network_vars.json packer.json'
alias tf_init='terraform init -var-file=../../terraform.tfvars'
alias tf_plan='terraform plan -var-file=../../terraform.tfvars'
alias tf_apply='terraform apply -var-file=../../terraform.tfvars'
alias tf_destroy='terraform destroy -var-file=../../terraform.tfvars'
