alias pk_create='packer build --var-file=../../config/config.json --var-file=../../config/other.json --var-file=../../config/bastion.json --var-file=../../config/version.json packer.json'
alias tf_init='terraform init -input=false -var-file=../../config/config.json -var-file=../../config/other.json -var-file=../../config/network.json -var-file=../../config/consul.json -var-file=../../config/version.json'
alias tf_plan='terraform plan -input=false -out=tfplan -var-file=../../config/config.json -var-file=../../config/other.json -var-file=../../config/network.json -var-file=../../config/consul.json -var-file=../../config/version.json'
alias tf_apply='terraform apply -input=false tfplan'
alias tf_destroy='terraform destroy -force -var-file=../../config/config.json -var-file=../../config/other.json -var-file=../../config/network.json -var-file=../../config/consul.json -var-file=../../config/version.json'
alias tf_refresh='terraform refresh -input=false -var-file=../../config/config.json -var-file=../../config/other.json -var-file=../../config/network.json -var-file=../../config/consul.json -var-file=../../config/version.json'
