# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "nextbreakpoint-tfstate"
    dynamodb_table = "nextbreakpoint-tfstate"
    encrypt        = true
    key            = "openvpn/terraform.tfstate"
    region         = "eu-west-2"
  }
}
