# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "aws_region" {
  default = "eu-west-2"
}

### MANDATORY ###
variable "environment" {}

### MANDATORY ###
variable "colour" {}

### MANDATORY ###
variable "bucket_name" {}
