# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
### MANDATORY ###
variable "aws_region" {}

### MANDATORY ###
variable "environment" {}

### MANDATORY ###
variable "colour" {}

### MANDATORY ###
variable "terraform_bucket_name" {}
